
%% Maschinen Parameter

% Elektrisch
% -------------------------------------------------------------------
%  Generated by MATLAB on 25-Jan-2016 11:23:15
%  MATLAB version: 8.3.0.532 (R2014a)
% -------------------------------------------------------------------
                                   

I_magnet = 10;
Lr_plus = 0.01;
LR_plus = 0.1;
RR_plus = 1;
Rs = 1;
PsiR_plus = 1;
Lsigma_plus = 0.01;


% Mechanisch
p = 2;
J = 0.16;
Rreib = 0.16;

%% Simulationsparameter
MLast = 0;
MASM = 25
;

%%Parameter speichern
save('parameter.mat');

